services:
  - type: web
    name: note-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
     python manage.py migrate && gunicorn note_app.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: PYTHON_VERSION
        value: 3.11
